"""population_bigint

Revision ID: 60fb13540f71
Revises: fdbc615ea0d5
Create Date: 2026-02-12 22:17:46.608247
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60fb13540f71'
down_revision: Union[str, None] = 'fdbc615ea0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('terrain', sa.String(length=100), nullable=True),
    sa.Column('admin_level_1', sa.String(length=255), nullable=True),
    sa.Column('admin_level_2', sa.String(length=255), nullable=True),
    sa.Column('admin_level_3', sa.String(length=255), nullable=True),
    sa.Column('admin_level_4', sa.String(length=255), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_type'), 'locations', ['type'], unique=False)
    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.DateTime(), nullable=False),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('astronomy_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.DateTime(), nullable=True),
    sa.Column('sunset', sa.DateTime(), nullable=True),
    sa.Column('day_length_hours', sa.Float(), nullable=True),
    sa.Column('moon_phase', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_astronomy_data_date'), 'astronomy_data', ['date'], unique=False)
    op.create_index(op.f('ix_astronomy_data_location_id'), 'astronomy_data', ['location_id'], unique=False)
    op.create_table('location_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_connections_from_id'), 'location_connections', ['from_id'], unique=False)
    op.create_index(op.f('ix_location_connections_to_id'), 'location_connections', ['to_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('visibility_km', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('conditions', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_datetime'), 'weather_data', ['datetime'], unique=False)
    op.create_index(op.f('ix_weather_data_location_id'), 'weather_data', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_location_id'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_datetime'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_location_connections_to_id'), table_name='location_connections')
    op.drop_index(op.f('ix_location_connections_from_id'), table_name='location_connections')
    op.drop_table('location_connections')
    op.drop_index(op.f('ix_astronomy_data_location_id'), table_name='astronomy_data')
    op.drop_index(op.f('ix_astronomy_data_date'), table_name='astronomy_data')
    op.drop_table('astronomy_data')
    op.drop_table('world_state')
    op.drop_index(op.f('ix_locations_type'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
